server:
  port: 8089
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka/
zuul:
  ignored-services: "*"
  routes:
      app-server: /app/**
      user-server: /user/**
