eureka:
  client:
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: app-server
feign:
    hystrix:
      enabled: true